create table student (
no number(2),
name varchar(10),
marks number(3));

select * from student;

insert into student values(
1,'sudha',100);

insert into student values(
2,'saketh',200);

insert into student values(
&no,
'&name',
&marks);

insert into student (
no,
name) values(
3,'Ramesh');

insert into student(
no,
name) values(
4,'Madhu');

select * from student;

insert into student(
no,name) values(
&no,&name);

alter table student add sdob date;

alter table student modify marks number(5);

ALTER TABLE STUDENT RENAME COLUMN MARKS TO SMARKS;

SELECT * FROM STUDENT ;

ALTER TABLE STUDENT SET UNUSED COLUMN SDOB;

SELECT * FROM STUDENT;

ALTER TABLE STUDENT DROP UNUSED COLUMN;

SELECT * FROM STUDENT;


--for RENAMING THE TABLE
rename student to stud;

COMMIT;

SELECT * FROM STUDENT ;

ROLLBACK;

SELECT  * FROM STUD;

RENAME STUD TO STUDENT;

SELECT * FROM STUDENT;

RENAME STUDENT TO STUD;

CREATE TABLE STUDENT (
NO NUMBER,
NAME VARCHAR2(20),
MARKS NUMBER);

INSERT INTO  STUDENT (
NO,NAME,MARKS) VALUES(
&NO,&NAME,&MARKS);

SAVEPOINT S4;

SELECT * FROM STUDENT;

ROLLBACK TO S3;

SELECT * FROM STUDENT;

ROLLBACK TO S2;

SELECT * FROM STUDENT ;

ROLLBACK TO S1;

SELECT * FROM STUDENT;

SELECT * FROM SHUBHAM.STUDENT;

GRANT SELECT ON STUDENT TO INVENTORY1;

SELECT * FROM INVENTORY1.STUDENT;


REVOKE SELECT ON STUDENT FROM INVENTORY1;


SELECT * FROM STUDENT;

DROP TABLE STUDENT;

SELECT * FROM STUD;

CREATE TABLE NEWSTUD AS (SELECT * FROM STUD);

SELECT * FROM NEWSTUD;
 
CREATE TABLE NEW1STUD(NO1,NUM2,NUM3) AS 
SELECT * FROM NEWSTUD;

SELECT * FROM NEW1STUD;

CREATE TABLE NEW2STUD(NO1,NO2) AS SELECT NO,NAME FROM
STUD;

SELECT * FROM NEW2STUD;

CREATE TABLE NEW3STUD (NUM1,NUM2,NUM3)
AS SELECT * FROM STUD WHERE NO = 2;

SELECT * FROM NEW3STUD;

DROP TABLE NEW3STUD;

INSERT INTO NEW3STUD SELECT * FROM STUD;

SELECT * FROM NEW3STUD;

SELECT * FROM NEW3STUD;

SELECT * FROM STUD;
ALTER TABLE STUD RENAME COLUMN NO TO NUMBERs;

SELECT * FROM NEW3STUD;

MERGE INTO NEW3STUD T
USING STUD S
On (S.numbers = T.NUM1)
WHEN MATCHED THEN
UPDATE SET T.NUM2 = S.NAME 
WHEN NOT MATCHED THEN
INSERT (S.numbers,S.NAME,S.SMARKS)
VALUES (T.NUM1,T.NUM2,T.NUM3);

--
CREATE TABLE SourceProducts(
    ProductID		INT,
    ProductName		VARCHAR(50),
    Price			DECIMAL(9,2)
);

INSERT INTO SourceProducts(ProductID,ProductName, Price) VALUES(1,'Table',100);
INSERT INTO SourceProducts(ProductID,ProductName, Price) VALUES(2,'Desk',80);
INSERT INTO SourceProducts(ProductID,ProductName, Price) VALUES(3,'Chair',50);
INSERT INTO SourceProducts(ProductID,ProductName, Price) VALUES(4,'Computer',300);


CREATE TABLE TargetProducts(
    ProductID		INT,
    ProductName		VARCHAR(50),
    Price			DECIMAL(9,2)
);

    
INSERT INTO TargetProducts(ProductID,ProductName, Price) VALUES(1,'Table',100);
INSERT INTO TargetProducts(ProductID,ProductName, Price) VALUES(2,'Desk',180);
INSERT INTO TargetProducts(ProductID,ProductName, Price) VALUES(5,'Bed',50);
INSERT INTO TargetProducts(ProductID,ProductName, Price) VALUES(6,'Cupboard',300);


SELECT * FROM SourceProducts;
SELECT * FROM TargetProducts;

merge into targetproducts t
using sourceproducts s
on t.productid  = s.productid
when matched then
update set t.price = s.price;


MERGE into TargetProducts  Target
USING SourceProducts	 Source
ON Source.ProductID = Target.ProductID
WHEN NOT MATCHED  THEN
INSERT (ProductID,ProductName, Price) 
VALUES (Source.ProductID,Source.ProductName, Source.Price);


CREATE TABLE people_source ( 
  person_id  INTEGER NOT NULL PRIMARY KEY, 
  first_name VARCHAR2(20) NOT NULL, 
  last_name  VARCHAR2(20) NOT NULL, 
  title      VARCHAR2(10) NOT NULL 
);

CREATE TABLE people_target ( 
  person_id  INTEGER NOT NULL PRIMARY KEY, 
  first_name VARCHAR2(20) NOT NULL, 
  last_name  VARCHAR2(20) NOT NULL, 
  title      VARCHAR2(10) NOT NULL 
);

INSERT INTO people_target VALUES (1, 'John', 'Smith', 'Mr');
INSERT INTO people_target VALUES (2, 'alice', 'jones', 'Mrs');
INSERT INTO people_source VALUES (2, 'Alice', 'Jones', 'Mrs.');
INSERT INTO people_source VALUES (3, 'Jane', 'Doe', 'Miss');
INSERT INTO people_source VALUES (4, 'Dave', 'Brown', 'Mr');

COMMIT;

select * from people_target;
select * from people_source;

merge into people_target t
using people_source s
on (s.person_id = t.person_id)
when not matched then
insert (person_id,first_name,last_name,title)
values (person_id,first_name,last_name,title);

--insert muliple

select * from student;
insert all
into student values(1,'a',100)
into student values(2,'b',200)
into student values(3,'c',300)
select * from stud;
rollback;
--
--create table dept (
--deptno number,
--dname varchar2(20),
--loc varchar2(20));
--
--insert into dept (deptno,dname,loc)values(
--10,'accounting','new york'),
--(20,'research','dallas'),
--(30,'sales','Chicago'),
--(40,'operation','bostan


functions

--abs
select abs(50),abs(-40),abs(0),abs(null) from dual;

--sign

select sign(5),sign(-6),sign(0),sign(null) from dual;

--sqrt
select sqrt(4),sqrt(0),sqrt(null),sqrt(1) from dual;

select numbers,name,nvl(smarks,300) from stud;
select * from stud;


--sysdate

select sysdate from dual;
select current_date,sysdate from dual;
select current_timestamp,current_date,sysdate from dual;
select systimestamp from dual;

select localtimestamp from dual;

slect dbtimezone from dual;

select sessiontimezone from dual;

select to_char(sysdate,'DD MONTH YYYY HH:MI:SS AM DY') from dual;

SELECT TO_CHAR(TO_DATE('26/DEC/2018','DD MON YYYY'),'DD * MONTH * DAY') FROM DUAL;

select months_between(to_date('26-AUG-2019','DD-MON-YYYY'),to_date('26-JAN-2019','DD-MON-YYYY')) FROM DUAL;

SELECT TRUNC(TO_DATE(20220101,'YYYYMMDD'),'MONTH')
FROM DUAL;

SELECT TO_DATE(20220101,'YYYYMMDD') FROM DUAL;


SELECT UID FROM DUAL;
SELECT USER FROM DUAL;

--DATE 03/01/22
--PRIMARY FOREIGN KEY

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
NO NUMBER NOT NULL,
NAME VARCHAR2(20),
MARKS NUMBER(3));

INSERT INTO STUDENT (
NAME,MARKS)VALUES(
'SHUBHAM',100);

CREATE TABLE STUDENT (
NO NUMBER CONSTRAINT NN NOT NULL,
NAME VARCHAR2(20),
MARKS NUMBER(3));

INSERT INTO STUDENT(
NAME,
MARKS) VALUES ('SHUBHAM',100);

INSERT INTO STUDENT VALUES(
1,'SHUBHAM',200);

SELECT * FROM STUDENT;

TRUNCATE TABLE STUDENT;

SELECT * FROM STUDENT;

DROP TABLE STUDENT;

CREATE TABLE STUDENT(
NO NUMBER NOT  NULL,
NAME VARCHAR2(20),
MARKS NUMBER CHECK (MARKS < 200));

INSERT INTO STUDENT VALUES(1,'SHUBHAM',400);

INSERT INTO STUDENT VALUES (1,'SHUBHAM',199);

SELECT * FROM STUDENT;

TRUNCATE TABLE STUDENT;

DROP TABLE STUDENT;

CREATE TABLE STUDENT(
NO NUMBER CONSTRAINT NN NOT NULL,
NAME VARCHAR2(20),
MARKS NUMBER CONSTRAINT CH CHECK (MARKS < 200));

INSERT INTO STUDENT VALUES(1,'SHUBHAM',199);

SELECT * FROM STUDENT;

TRUNCATE TABLE STUDENT;

DROP TABLE STUDENT;

--PRIMARY KEY

CREATE TABLE STUDENT(
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(30),
MARKS NUMBER);

INSERT INTO STUDENT VALUES (&NO,&NAME,&MARKS);

TRUNCATE TABLE STUDENT;

DROP TABLE STUDENT;

CREATE TABLE STUDENT(
NO NUMBER CONSTRAINT PK PRIMARY KEY,
NAME VARCHAR2(20),
MARKS NUMBER);

INSERT INTO STUDENT VALUES(&NO,&NAME,&MARKS);

TRUNCATE TABLE STUDENT;

DROP TABLE STUDENT;

--FOREIGN KEY

CREATE TABLE DEPT(DEPTNO NUMBER CONSTRAINT PK PRIMARY KEY,
DNAME VARCHAR2(20),
LOCATION VARCHAR2(20));

DROP TABLE DEPT;

insert into dept values (10,'Accounting','New York');

insert into dept values (20,'Research','Dallas');

insert into dept values (30,'Sales','Chicago');

insert into dept values (40,'Operations','Boston');

CREATE TABLE EMP(EMPNO NUMBER,
EMPNAME VARCHAR2(20),
DEPTNO NUMBER,CONSTRAINT FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO));

DROP TABLE EMP;

INSERT INTO EMP VALUES(
2,'RAHUL',20);

DELETE FROM EMP WHERE DEPTNO = 20;
ROLLBACK;
SELECT * FROM DEPT;

SELECT * FROM EMP;

CREATE TABLE DOC(
DOCID NUMBER PRIMARY KEY,
DOCNAME VARCHAR2(20));

CREATE TABLE DOCINFO(
IDS NUMBER,
LOC VARCHAR2(20),CONSTRAINT FK FOREIGN KEY(IDS) REFERENCES DOC(DOCID));

DROP TABLE DOCINFO;

SELECT * FROM DOC;

INSERT INTO DOC VALUES(&DOCID,&DOCNAME);

CREATE TABLE DOCINFO(
DOCID NUMBER,
LOC VARCHAR2(20),
FOREIGN KEY(DOCID) REFERENCES DOC(DOCID));

INSERT INTO DOCINFO VALUES(
3,'TIRODA');

SELECT * FROM DOCINFO;
SELECT * FROM DOC;


SELECT 
D.DOCID,
D.DOCNAME,
DC.LOC FROM DOC D ,DOCINFO DC WHERE D.DOCID = DC.DOCID;

DELETE FROM DOC WHERE DOCID = 1;
SELECT * FROM DUAL;


--TYPE IN SQL
CREATE TYPE ADDR AS OBJECT(HNO NUMBER,CITY VARCHAR2(20));/
DROP TYPE ADDR;

DROP TABLE STUDENT;

CREATE TABLE STUDENT(ID NUMBER,NAME VARCHAR2(20),ADDRESS ADDR);

INSERT INTO STUDENT VALUES(3,'HOMIT',ADDR(345,'MALI'));

SELECT S.ID,S.NAME,S.ADDRESS.HNO HOUSENUMBER,S.ADDRESS.CITY CITY FROM STUDENT S;

UPDATE STUDENT S SET S.ADDRESS.CITY = 'NAGPUR' WHERE S.ADDRESS.HNO = 234;

DELETE FROM STUDENT S WHERE S.ADDRESS.HNO = 123;

SELECT S.ID,S.NAME,S.ADDRESS.HNO,S.ADDRESS.CITY FROM STUDENT S;

DROP TYPE ADDR;

DROP TABLE STUDENT;

DROP TYPE ADDR;




--sql new

select * from hr.employees;
-- INSTR FUNCTION (COLUMN,'SRING')
select first_name,last_name,phone_number,instr(phone_number,'5') from hr.employees;
-- USING LPAD AND RPAD FOR ADDING STRING 
SELECT FIRST_NAME FROM HR.EMPLOYEES;
-- USING LPAD
SELECT FIRST_NAME,LPAD(FIRST_NAME,10,'*') FROM HR.EMPLOYEES;
-- USING RPAD


-- USIGN TO_CHAR FUNCTION GIVEN COLUMN TO STRING
SELECT SALARY FROM HR.EMPLOYEES;

SELECT TO_CHAR(SALARY,'L99G999') FROM HR.EMPLOYEES;

-- TO_CHAR WITH DATE
SELECT FIRST_NAME,HIRE_DATE FROM HR.EMPLOYEES;
SELECT FIRST_NAME,TO_CHAR(HIRE_DATE,'YYYY-MM-DD') FROM HR.EMPLOYEES;
SELECT COUNT(FIRST_NAME),TO_CHAR(HIRE_DATE,'YYYY/MM/DD') FROM HR.EMPLOYEES GROUP BY HIRE_DATE;

-- FOR FILTERING DATE
SELECT FIRST_NAME,HIRE_DATE FROM HR.EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'MON') = 'JAN';

-- FOR PROBLEM
SELECT FIRST_NAME,HIRE_DATE FROM HR.EMPLOYEES WHERE HIRE_DATE >= (SELECT MIN(HIRE_DATE) FROM HR.EMPLOYEES) AND HIRE_DATE <= (SELECT ADD_MONTHS(MIN(HIRE_DATE),120) FROM HR.EMPLOYEES); 

-- USING ROUND

SELECT * FROM HR.EMPLOYEES;
SELECT ROUND(999.76970,1) FROM DUAL;

-- USING TRUNC FUNCTION

SELECT TRUNC(999.76970,1) FROM DUAL;

-- USING SYSDATE
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YY HH24:MI:SS') FROM DUAL;

-- USING SYSTIMESTAMP
SELECT SYSTIMESTAMP,TO_CHAR(SYSDATE,'DD-MON-YY HH.MI.SS') FROM DUAL;

-- USING MONTHS_BETWEEN
SELECT * FROM DUAL;

SELECT SYSDATE,HIRE_DATE FROM HR.EMPLOYEES;


-- USING ADD_MONTHS

SELECT SYSDATE,ADD_MONTHS(SYSDATE,1),ADD_MONTHS(SYSDATE,2),ADD_MONTHS(SYSDATE,3) FROM DUAL;

-- USING JOIN

SELECT * FROM HR.EMPLOYEES;
SELECT * FROM HR.DEPARTMENTS;

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID FROM HR.EMPLOYEES;

--INNER JOIN
SELECT HR.EMPLOYEES.FIRST_NAME,HR.EMPLOYEES.LAST_NAME,HR.DEPARTMENTS.DEPARTMENT_NAME
FROM HR.EMPLOYEES INNER JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID;

SELECT HR.EMPLOYEES.FIRST_NAME,HR.EMPLOYEES.LAST_NAME,HR.DEPARTMENTS.DEPARTMENT_NAME
FROM HR.EMPLOYEES LEFT JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID WHERE HR.DEPARTMENTS.DEPARTMENT_NAME = NULL;

-- RIGHT JOIN

SELECT HR.EMPLOYEES.FIRST_NAME,HR.EMPLOYEES.LAST_NAME,HR.DEPARTMENTS.DEPARTMENT_NAME
FROM HR.EMPLOYEES RIGHT JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID;


-- FULL OUTER JOIN

SELECT HR.EMPLOYEES.FIRST_NAME,HR.EMPLOYEES.LAST_NAME,HR.DEPARTMENTS.DEPARTMENT_NAME
FROM HR.EMPLOYEES FULL JOIN HR.DEPARTMENTS ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID;

-- CREATING THE NEW TABLE
CREATE TABLE 
TEST_TABLE1 (
COL1 VARCHAR(100),
COL2 NUMBER(5));

SELECT * FROM TEST_TABLE1;

-- INSERT INTO TEST
INSERT INTO TEST_TABLE1 VALUES('HELLO',4);
INSERT INTO TEST_TABLE1 VALUES('WORLD',5);
SELECT  * FROM TEST_TABLE1;

INSERT INTO TEST_TABLE1 (COL1,COL2) VALUES('FOO',6);
INSERT INTO TEST_TABLE1 (COL1) VALUES('BAR');

SELECT * FROM TEST_TABLE1;

-- COMMIT AND ROLLBACK

ROLLBACK;

SELECT * FROM TEST_TABLE1;
COMMIT;

-- delete command

SELECT * FROM TEST_TABLE1;
DELETE FROM TEST_TABLE1 WHERE COL2 = 4;

DELETE FROM TEST_TABLE1;
ROLLBACK;

-- MULTIPLE TRANSACTION

INSERT INTO TEST_TABLE1 VALUES('ANOTHER NEW_ROW',2);

UPDATE TEST_TABLE1 SET COL1 = 'UPDATED!' WHERE COL2 = 2;
SELECT * FROM TEST_TABLE1;
ROLLBACK;

-- TRUNCATE
SELECT * FROM TEST_TABLE1;
TRUNCATE TABLE TEST_TABLE1;

SELECT * FROM TEST_TABLE1;

-- ADDING OR DROPING 
ALTER TABLE TEST_TABLE1 ADD(COL3 NUMBER(10));

SELECT * FROM TEST_TABLE1;

INSERT INTO TEST_TABLE1 VALUES('HELLO',1,2);
SELECT * FROM TEST_TABLE1;

ALTER TABLE TEST_TABLE1 DROP COLUMN COL3SELECT * FROM TEST_TABLE1;
SELECT * FROM TEST_TABLE1;

-- AGGREGATE FUNCTION

SELECT MAX(SALARY),MIN(SALARY),ROUND(AVG(SALARY)),COUNT(*) FROM HR.EMPLOYEES;
SELECT SUM(SALARY) FROM HR.EMPLOYEES;

-- USING GRUOUP BY
SELECT COUNT(*) NUM_EMPLOYEES,DEPARTMENT_ID FROM HR.EMPLOYEES GROUP  BY DEPARTMENT_ID ORDER BY NUM_EMPLOYEES DESC;

-- USING GROUP BY WITH MIN MAX AVG
SELECT ROUND(AVG(SALARY)),MIN(SALARY),MAX(SALARY),DEPARTMENT_ID FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT ROUND(AVG(SALARY)),MIN(SALARY),MAX(SALARY),DEPARTMENT_ID FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

-- USING HAVING

SELECT ROUND(AVG(SALARY)),MAX(SALARY),DEPARTMENT_ID FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) > 9000 AND MAX(SALARY) < 15000;

-- USING PRIMARY KEY
-- CONSTRAINTS

CREATE TABLE DEMO_TABLE2(COL1 NUMBER(5) PRIMARY KEY,
COL2 VARCHAR2(20));

INSERT INTO DEMO_TABLE2 VALUES(1,'HELLO');
INSERT INTO DEMO_TABLE2 VALUES(2,'HELLO');

SELECT * FROM DEMO_TABLE2;

INSERT INTO DEMO_TABLE2 VALUES(NULL,'FF');

-- USIGN NOT NULL
INSERT INTO DEMO_TABLE2(COL1) VALUES(3);

SELECT * FROM DEMO_TABLE2;

DROP TABLE DEMO_TABLE2;
CREATE TABLE DEMO_TABLE2(COL1 NUMBER(5) PRIMARY KEY,
COL2 VARCHAR2(20) NOT NULL);

INSERT INTO DEMO_TABLE2 (COL1) VALUES(5);--GIVING ERROR

-- CHECK CONSTRAINT
CREATE TABLE DEMO_TABLE (
ID NUMBER,NAME VARCHAR2(50),
CONSTRAINT CHECK_UPPER_CASE_NAME
CHECK(NAME = UPPER(NAME)));

INSERT INTO DEMO_TABLE VALUES(1,'HELLO');

SELECT * FROM DEMO_TABLE;

INSERT INTO DEMO_TABLE VALUES(2,'hello');

-- USING FOREIGN KEY
CREATE TABLE SUPPLIERS(ID NUMBER(10) PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL);

CREATE TABLE PROUCT(ID NUMBER(10) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
SUPPLIER_ID NUMBER(10) NOT NULL,
CONSTRAINT FK FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(ID));

INSERT INTO SUPPLIERS VALUES(1,'LINKEDEN');
INSERT INTO SUPPLIERS VALUES(2,'FACEBOOK');
INSERT INTO PROUCT VALUES(20,'ORACLE TRAINING',1);

SELECT * FROM SUPPLIERS;
SELECT * FROM PROUCT;

INSERT INTO PROUCT VALUES(21,'RAMO',2); --ERROR
INSERT INTO PROUCT VALUES(21,'RAMO',2);


-- SUBQUERY

SELECT * FROM HR.DEPARTMENTS;
SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 20;


SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DISTINCT(DEPARTMENT_ID) FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 20);
SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS WHERE DEPARTMENT_NAME = 'Marketing');

